#!/usr/bin/env bash
#Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'mkdir /etc/nginx/html'
sudo sh -c 'touch /etc/nginx/html/index.html'
sudo sh -c 'echo "Hello World!" > /etc/nginx/html/index.html'
sudo sh -c 'touch /etc/nginx/html/custom_404.html'
sudo sh -c 'echo "Ceci n'est pas une page" > /etc/nginx/html/custom_404.html'

sudo sh -c 'printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://github.com;
    }

    error_page 404 /custom_404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
