#!/usr/bin/env bash
# Script that starts nginx as nginx user

# Ensure correct permissions for nginx.conf
chmod 644 /etc/nginx/nginx.conf

# Update the user in nginx.conf to nginx
sed -i -E 's/^\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf

# Update the default site configuration to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Stop Apache if it's running
sudo pkill apache2

# Restart Nginx with sudo
sudo service nginx restart
