#!/usr/bin/env bash
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user www-data;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
mkdir -p /run/nginx
service nginx restart

