#!/usr/bin/env bash

#configure to our needs so as to connect to a server without a password.

cat <<EOF > ~/.ssh/config
Host Cserver01
  Hostname 54.172.224.134
  User ubuntu
  IdentityFile ~/.ssh/school
  PasswordAuthentication no
EOF
